package org.go.sopt.winey.presentation.model

enum class NotificationType(val key: String) {
    RANK_UP_TO_2("RANKUPTO2"),
    RANK_UP_TO_3("RANKUPTO3"),
    RANK_UP_TO_4("RANKUPTO4"),
    RANK_DOWN_TO_1("DELETERANKDOWNTO1"),
    RANK_DOWN_TO_2("DELETERANKDOWNTO2"),
    RANK_DOWN_TO_3("DELETERANKDOWNTO3"),
    GOAL_FAILED("GOALFAILED"),
    LIKE_NOTIFICATION("LIKENOTI"),
    COMMENT_NOTIFICATION("COMMENTNOTI"),
    HOW_TO_LEVEL_UP("HOWTOLEVELUP")
}
